### ISSUE TITLE
Uncaught Error: Undefined constant "WP_IMGIX_SIGNING_TOKEN

### ISSUE THREAD

**Issue by maximus-lynn** [rsoury/wp-imgix#5]
Uncaught Error: Undefined constant "WP_IMGIX_SIGNING_TOKEN

We don't enable our images for url signing to be used so have added the code below to my WP-config and not added the other line:
`define( 'WP_IMGIX_URL', 'https://marquee.imgix.net');`

But when I do I get the error in the title that says that WP_IMGIX_SIGNING_TOKEN is undefined. 

It sounded like in the readme that this is an optional define to implement. 

As we aren't using url signing in imgix what is the recommendation in these cases?

**Comment by rsoury** [comment]
Hi @maximus-lynn ,

This is now solved in https://github.com/rsoury/wp-imgix/commit/a32e3cfb187beb4d5730cd1fd442155b1a774d5e

I hope the delay was not too inconvenient.
I did not realise there were active users.
